from abc import ABC, abstractmethod

class IShape(ABC):
    @abstractmethod
    def draw(self, p): ...

    @abstractmethod
    def contains(self, pt): ...

    @abstractmethod
    def set_selected(self, v): ...

    @abstractmethod
    def is_selected(self): ...

    @abstractmethod
    def rect(self): ...

    @abstractmethod
    def set_rect(self, rect, bounds=None): ...

    @abstractmethod
    def move(self, dx, dy, bounds): ...

    @abstractmethod
    def change_size(self, d, bounds): ...

    @abstractmethod
    def set_fill_color(self, color): ...

    @abstractmethod
    def set_line_color(self, color): ...

    @abstractmethod
    def type_name(self): ...

    @abstractmethod
    def save(self, stream): ...

    @abstractmethod
    def load(self, stream, factory=None): ...
